// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateDatabaseResponse struct {
	Created *int `json:"created,omitempty"`
}

type CreateTableData struct {
	ColName *string           `json:"colName,omitempty"`
	Props   *CreateTableProps `json:"props,omitempty"`
}

type CreateTableProps struct {
	Type     *string     `json:"type,omitempty"`
	Nullable *bool       `json:"nullable,omitempty"`
	Default  interface{} `json:"default,omitempty"`
	Unique   *bool       `json:"unique,omitempty"`
}

type CreateTableResponse struct {
	Created *string `json:"created,omitempty"`
}

type TableInfo struct {
	Field   *string     `json:"field,omitempty"`
	Type    *string     `json:"type,omitempty"`
	Null    *string     `json:"null,omitempty"`
	Key     *string     `json:"key,omitempty"`
	Default interface{} `json:"default,omitempty"`
	Extra   interface{} `json:"extra,omitempty"`
}
