// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Data used when adding or updating a column
type AddUpdateColumnData struct {
	// Column name
	ColName *string `json:"colName,omitempty"`
	// Column data type
	Type *string `json:"type,omitempty"`
}

// Several info about a table column
type ColumnInfo struct {
	// Column name
	Name *string `json:"name,omitempty"`
	// Column data type
	Type *string `json:"type,omitempty"`
	// If the table accepts null values or not
	Nullable *string `json:"nullable,omitempty"`
	// Constraint name of the column, e.g PRI
	Key interface{} `json:"key,omitempty"`
	// Column default value
	Default interface{} `json:"default,omitempty"`
}

// General data about the column to create
type CreateColumnData struct {
	// Column name
	ColName *string `json:"colName,omitempty"`
	// Data type of the column
	Type *string `json:"type,omitempty"`
	// Wether the column accepts null values
	Nullable *bool `json:"nullable,omitempty"`
	// Default value of the column
	Default interface{} `json:"default,omitempty"`
	// Wether to add unique constraint on the column
	Unique *bool `json:"unique,omitempty"`
}

// Table created successfully
type CreateTableResponse struct {
	// Name of created table
	Created string `json:"created"`
}

type DeleteColumnData struct {
	// Deleted column name
	ColName *string `json:"colName,omitempty"`
}

// Generic operation success response
type SuccessResponse struct {
	Success bool `json:"success"`
}
