// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Kareem Ebrahim",
            "email": "kareemmahlees@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get info about the api",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/default_routes.APIInfoResult"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "check application health by getting current date",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/default_routes.HealthCheckResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "default_routes.APIInfoResult": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "default_routes.HealthCheckResult": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MySQL Meta",
	Description:      "A RESTFull and GraphQL API to manage your MySQL DB",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
