basePath: /
definitions:
  databases.HandleCreateDatabaseResult:
    properties:
      created:
        type: integer
    type: object
  databases.HandleListDatabasesResult:
    properties:
      databases:
        items:
          type: string
        type: array
    type: object
  default_routes.APIInfoResult:
    properties:
      author:
        type: string
      contact:
        type: string
      repo:
        type: string
      year:
        type: integer
    type: object
  default_routes.HealthCheckResult:
    properties:
      date:
        type: string
    type: object
host: localhost:4000
info:
  contact:
    email: kareemmahlees@gmail.com
    name: Kareem Ebrahim
  description: A RESTFull and GraphQL API to manage your MySQL DB
  title: MySQL Meta
  version: "1.0"
paths:
  /:
    get:
      description: get info about the api
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/default_routes.APIInfoResult'
      tags:
      - default
  /databases:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/databases.HandleListDatabasesResult'
      tags:
      - Databases
    post:
      description: create database
      parameters:
      - description: database name
        in: path
        name: name
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/databases.HandleCreateDatabaseResult'
      tags:
      - Databases
  /health:
    get:
      description: check application health by getting current date
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/default_routes.HealthCheckResult'
      tags:
      - default
swagger: "2.0"
