name: Lint
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - name: Run gqlgen generate
        run: make graphql
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
